//------------------------------------------------------------------------
// Copyright(c) 2023 aikelab.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"NoteNameDemo.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"NoteNameDemo VST3 (64Bit)"
#else
#define stringFileDescription	"NoteNameDemo VST3"
#endif
#define stringCompanyName		"aikelab\0"
#define stringLegalCopyright	"Copyright(c) 2023 aikelab."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
